spring.application.name=streamEra

# DB
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5454/streamera}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database=postgresql

# DB behaivor
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


# GraphQl
spring.graphql.graphiql.enabled=true